# Generated by Django 3.0.5 on 2021-03-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('topping', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=10)),
                ('pizza_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra large', 'Extra large')], default='Small', max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('topping', models.ManyToManyField(default='Tomato', to='pizza.Topping')),
            ],
        ),
    ]
