# Generated by Django 3.0.5 on 2021-03-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('topping', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=10)),
                ('customer_name', models.CharField(max_length=30)),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Size')),
                ('topping', models.ManyToManyField(default='Tomato', to='pizza.Topping')),
            ],
        ),
    ]
